version: "3.9"
services:
  database: 
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: toto
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
